export const products = [
    {
      id: 1,
      name: 'Smartphone X1',
      description: 'A high-end smartphone with advanced features.',
      price: 79999.99,
      image: 'https://m.media-amazon.com/images/I/71geVdy6-OS._SX679_.jpg',
      icon: '📱',
    },
    {
      id: 2,
      name: 'Wireless Earbuds',
      description: 'Noise-cancelling earbuds with long battery life.',
      price: 19999.99,
      image: 'https://m.media-amazon.com/images/I/61mpMH5TzkL._SX679_.jpg',
      icon: '🎧',
    },
    {
      id: 3,
      name: 'Gaming Laptop',
      description: 'A powerful laptop for gaming and productivity.',
      price: 129999.99,
      image: 'https://m.media-amazon.com/images/I/71ZDY57yTQL._SX679_.jpg',
      icon: '💻',
    },
    {
      id: 4,
      name: 'Smartwatch Pro',
      description: 'Feature-packed smartwatch for fitness and more.',
      price: 15999.99,
      image: 'https://m.media-amazon.com/images/I/61DUO0NqyyL._SX679_.jpg',
      icon: '⌚',
    },
    {
      id: 5,
      name: 'DSLR Camera',
      description: 'Capture stunning photos with this high-resolution camera.',
      price: 64999.99,
      image: 'https://m.media-amazon.com/images/I/81+H9O4nGAL._SX679_.jpg',
      icon: '📷',
    },
    {
      id: 6,
      name: 'Gaming Console',
      description: 'Next-gen console for immersive gaming experience.',
      price: 49999.99,
      image: 'https://m.media-amazon.com/images/I/71vFKBpKakL._SX679_.jpg',
      icon: '🎮',
    },
    {
      id: 7,
      name: '4K TV',
      description: 'Ultra HD television with vibrant colors and smart features.',
      price: 89999.99,
      image: 'https://m.media-amazon.com/images/I/81K4--W0+ZL._SX679_.jpg',
      icon: '📺',
    },
    {
      id: 8,
      name: 'Bluetooth Speaker',
      description: 'Portable speaker with powerful bass and Bluetooth connectivity.',
      price: 9999.99,
      image: 'https://m.media-amazon.com/images/I/71yOXgtV-uL._SX679_.jpg',
      icon: '🔊',
    },
    {
      id: 9,
      name: 'Wireless Keyboard & Mouse Combo',
      description: 'Ergonomic design with seamless wireless performance.',
      price: 3499.99,
      image: 'https://m.media-amazon.com/images/I/61OESWEf60L._SX679_.jpg',
      icon: '⌨️',
    },
    {
      id: 10,
      name: 'Action Camera',
      description: 'Compact camera for capturing action-packed adventures.',
      price: 24999.99,
      image: 'https://m.media-amazon.com/images/I/71PpAF8iFcL._SX679_.jpg',
      icon: '📹',
    },
    {
      id: 11,
      name: 'VR Headset',
      description: 'Explore virtual reality with this immersive headset.',
      price: 44999.99,
      image: 'https://m.media-amazon.com/images/I/71+J+K6aq9L._SX679_.jpg',
      icon: '🕶️',
    },
    {
      id: 12,
      name: 'Electric Scooter',
      description: 'Eco-friendly scooter with fast speeds and long battery.',
      price: 29999.99,
      image: 'https://m.media-amazon.com/images/I/91bL58AElbL._SX679_.jpg',
      icon: '🛴',
    },
    {
      id: 13,
      name: 'Smart Light Bulb',
      description: 'Energy-efficient and smart-controlled light bulb.',
      price: 1499.99,
      image: 'https://m.media-amazon.com/images/I/61n7sA0VYZL._SX679_.jpg',
      icon: '💡',
    },
    {
      id: 14,
      name: 'Electric Toothbrush',
      description: 'High-tech toothbrush with multiple cleaning modes.',
      price: 7999.99,
      image: 'https://m.media-amazon.com/images/I/71G+mR5yCrL._SX679_.jpg',
      icon: '🪥',
    },
    {
      id: 15,
      name: 'Portable Power Bank',
      description: 'Charge your devices on the go with this compact power bank.',
      price: 2999.99,
      image: 'https://m.media-amazon.com/images/I/71hKTkzxAAL._SX679_.jpg',
      icon: '🔋',
    },
  ];
  